### ISSUE TITLE
Comparsion with Image.prefetch

### ISSUE THREAD

**Issue by Emetrop** [lane-c-wagner/react-native-expo-cached-image#14]
What's different between Image.prefetch and your library and can it be used together somehow?

**Comment by lane-c-wagner** [comment]
It looks like its very similar, though I will admit I'm not super familiar with prefetch... I did a bit of searching for caching before creating this library and never came across it.

I guess the biggest difference is we plan to give more granular control of the cache itself, as well as caching in the component itself, without the need to call prefetch in the constructor.

I would recommend NOT using both.
