### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by jonathanroze** [lane-c-wagner/react-native-expo-cached-image#15]
Hi,

I'm trying to use your Image component but Expo return this error:

Version mismatch
Javascript version 0.61.4
Native version: 0.62.2

Thanks

**Comment by daksh23** [comment]
use in render method its solve your problem

**Comment by jdleo** [comment]
Also getting the same error

**Comment by jdleo** [comment]
For now, just fix this by writing the component yourself. (copy paste, takes 5 seconds)

Copy the code found in `index.js` of this repository and paste it in your `/components` , after, install the dependencies by doing

```
expo install expo-crypto
expo install expo-file-system
```

then import your new `CachedImage` component wherever you want from your `/components` directory.

**Comment by lane-c-wagner** [comment]
Just updated the package.json to allow newer versions.

**Comment by dhee9000** [comment]
still getting this issue on the latest version, it says JS version 0.63.3 Native version 0.62.2 (which is the version I am using)

**Comment by carissacks** [comment]
> still getting this issue on the latest version, it says JS version 0.63.3 Native version 0.62.2 (which is the version I am using). I am using the bare workflow if that makes a difference. Using @jdleo 's solution has resolved it for me for now

+1
