### ISSUE TITLE
Image corruption

### ISSUE THREAD

**Issue by yoeven** [lane-c-wagner/react-native-expo-cached-image#19]
Hi there, its a great library and a lifesaver! After integrating it into one of my applications there are moments where the image displayed is only half shown and the other half is grey. I tried to do some digging around to see if I can fix the problem my self but I can't seem too. I've listed some of my references below that face similar issues of the bug.

1. https://github.com/wcandillon/react-native-img-cache/issues/61
2. https://github.com/code-and-co/react-native-image-offline/issues/7
3. https://stackoverflow.com/questions/60075537/react-native-expo-filesystem-downloadasync-corrupted-images

I have tried it on multiple devices, and it seems that this happens more often lower-end devices while on modern devices this happens maybe once or twice and after restarting the app, the issue is gone.

**Comment by red-made** [comment]
Hi @yoeven did you have solved the issue? I'm still facing the same problem

**Comment by yoeven** [comment]
Hi @red-made, I did a test again and there still seems to be image corruption but it rare situation on android, trying to narrow down the cause, could you share more details on your environment
